# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, connection, haskeline, hslogger, httpConduit, httpTypes
, mtl, regexCompat
}:

cabal.mkDerivation (self: {
  pname = "hwall-auth-iitk";
  version = "0.1.0.1";
  src = /home/rejuvyesh/src/haskell/hwall-auth-iitk;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    connection haskeline hslogger httpConduit httpTypes mtl regexCompat
  ];
  meta = {
    description = "Initial version of firewall Authentication for IITK network";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
