# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdargs, waiAppStatic, warp }:

cabal.mkDerivation (self: {
  pname = "hserv";
  version = "0.1.0.3";
  src = /home/rejuvyesh/src/haskell/hserv;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ cmdargs waiAppStatic warp ];
  meta = {
    homepage = "http://github.com/rejuvyesh/hserv";
    description = "Simple http server in haskell";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
